---
- name: Install Apache Tomcat10
  hosts: webserver
  remote_user: devops
  become: yes
  tasks:
    - name: Create tomcat user
      user:
        name: tomcat

    - name: Create tomcat group
      group:
        name: tomcat

    - name: Install JAVA on RHEL family
      yum:
        name: java-latest-openjdk.x86_64
        state: present
      when: ansible_os_family=="RedHat"

    - name: Installing Java on Debian family 
      apt: 
        name: default-jre
        state: present 
        update_cache: yes
      when: ansible_os_family == "Debian" 

    - name: Create tomcat directory
      file:
        path: /opt/tomcat10
        owner: tomcat
        group: tomcat
        mode: 755
        state: directory

    - name: download & unarchive tomcat10
      unarchive:
        # most recent src: https://mirrors.estointernet.in/apache/tomcat/tomcat-10/v10.1.0-M14/bin/apache-tomcat-10.1.0-M14.tar.gz
        src: https://mirrors.estointernet.in/apache/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
        dest: /opt/tomcat10
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Change ownership of tomcat directory
      file:
        path: /opt/tomcat10
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory

    - name: Copy tomcat.service (already configured)
      copy:
        src: /home/devops/scripts/ansible/tomcat/tomcat.service
        dest: /etc/systemd/system/tomcat.service
        remote_src: yes
        mode: 0755

    - name: Copy tomcat-users.xml file
      copy:
        src: /home/devops/scripts/ansible/tomcat/tomcat-users.xml
        dest: /opt/tomcat/conf/tomcat-users.xml
        remote_src: yes
        mode: 0755

    - name: Copy tomcat-users.xml file
      copy:
        src: /home/devops/scripts/ansible/tomcat/context.xml
        dest: /opt/tomcat/webapps/manager/META-INF/context.xml
        remote_src: yes
        mode: 0755

    - name: Start and enable Tomcat10 on sever
      systemd:
        name: tomcat
        state: started
        daemon_reload: true
